package ClientServer;

public enum MessageType {
    ADDOPERATOR,
    DELETEOPERATOR,
    MODIFYPASSWORD,
    MODIFYUSERNAME,
    RETURNAVAILABLECHOICES,
    ADDOPERATION,
    DELETEOPERATION,
    MODIFYIDOPERATION,
    MODIFYTEXTOPERATION,
    JUSTTHEONEOPERATOR,
    LOGGED
}
